services:
  mysql:
    image: mysql:8
    container_name: mysql-linsi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red-linsi

  app:
    build: .
    container_name: springboot-linsi
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_NOMBRE: ${ADMIN_NOMBRE}
      ADMIN_APELLIDO: ${ADMIN_APELLIDO}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_DNI: ${ADMIN_DNI}
    depends_on:
      - mysql
    networks:
      - red-linsi

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-linsi
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - red-linsi

volumes:
  mysql_data:

networks:
  red-linsi:
